server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=TRUE&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    sentinel:
      transport:
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        output:
          destination: stream-test-topic
  application:
      name: content-center
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000


#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 1000

#  httpclient:
#    enabled: true
#    # feign的最大连接数
#    max-connections: 200
#    # feign单个路径的最大连接数
#    max-connections-per-route: 50
#    connection-timeout: 4000

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

management:
  endpoints:
    web:
      exposure:
        include: '*'

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group
logging:
  level:
    com.alibaba.nacos: error
